//------------------------------------//
//           「一年」 教育漢字           //
//------------------------------------//

//This is for mass importing into a group review.
if (typeof mass_import !== 'undefined')
	sectionmark[section_cnt++] = count;

addTerm("一", "ichi", "いち", "One;1", "It's a number based on stroke count.");
addTerm("二", "ni", "に", "Two;2", "It's a number based on stroke count.");
addTerm("三", "san", "さん", "Three;3", "It's a number based on stroke count.");
addTerm("四", "shi", "し", "Four;4", "It's a number.");
addTerm("五", "go", "ご", "Five;5", "It's a number.");
addTerm("六", "roku", "ろく", "Six;6", "It's a number.");
addTerm("七", "nana", "なな", "Seven;7", "It's a number.");
addTerm("八", "hachi", "はち", "Eight;8", "It's a number.");
addTerm("九", "kyuu", "きゅう", "Nine;9", "It's a number.");
addTerm("十", "juu", "じゅう", "Ten;10", "It's a number.");
addTerm("百", "hyaku", "ひゃく", "Hundred;One Hundred;100", "10x10");
addTerm("千", "sen", "せん", "Thousand;One Thousand;1000", "100x10.");
addTerm("上", "ue", "うえ", "Top;Above", "n/a");
addTerm("下", "shita", "した", "Bottom;Below", "n/a");
addTerm("左", "hidari", "ひだり", "Left", "n/a");
addTerm("右", "migi", "みぎ", "Right", "n/a");
addTerm("中", "naka", "なか", "Middle", "n/a");
addTerm("大", "oo", "おお", "Large", "n/a");
addTerm("小", "chii", "ちい", "Small", "n/a");
addTerm("月", "tsuki", "つき", "Moon;Month", "n/a");
addTerm("日", "hi", "ひ", "Sun;Day", "n/a");
addTerm("年", "toshi", "とし", "Year", "n/a");
addTerm("早", "haya", "はや", "Early", "n/a");
addTerm("木", "ki", "き", "Tree", "n/a");
addTerm("林", "hayashi", "はやし", "Forest", "n/a");
addTerm("山", "yama", "やま", "Mountain", "n/a");
addTerm("川", "kawa", "かわ", "River", "n/a");
addTerm("土", "tsuchi", "つち", "Soil", "n/a");
addTerm("空", "sora", "そら", "Sky", "n/a");
addTerm("田", "ta", "た", "Rice Paddy", "n/a");
addTerm("天", "ame", "あめ", "Heaven", "n/a");
addTerm("生", "i", "い", "Life", "n/a");
addTerm("花", "hana", "はな", "Flower", "n/a");
addTerm("草", "kusa", "くさ", "Grass", "n/a");
addTerm("虫", "mushi", "むし", "Insect", "n/a");
addTerm("犬", "inu", "いぬ", "Dog", "n/a");
addTerm("人", "hito", "ひと", "Person", "n/a");
addTerm("名", "na", "な", "Name", "n/a");
addTerm("女", "onna", "おんな", "Female", "n/a");
addTerm("男", "otoko", "おとこ", "Male", "n/a");
addTerm("子", "ko", "こ", "Child", "n/a");
addTerm("目", "me", "め", "Eye", "n/a");
addTerm("耳", "mimi", "みみ", "Ear", "n/a");
addTerm("口", "kuchi", "くち", "Mouth", "n/a");
addTerm("手", "te", "て", "Hand", "n/a");
addTerm("足", "ashi", "あし", "Foot", "n/a");
addTerm("見", "mi", "み", "See", "n/a");
addTerm("音", "oto", "おと", "Sound;Noise", "n/a");
addTerm("力", "chikari", "ちかり", "Power", "n/a");
addTerm("気", "ki", "き", "Spirit", "n/a");
addTerm("円", "en", "えん", "Yen", "n/a");
addTerm("入", "hai", "はい", "Enter", "n/a");
addTerm("出", "de", "で", "Exit", "n/a");
addTerm("立", "ta", "た", "Stand Up", "n/a");
addTerm("休", "yasu", "やす", "Rest", "n/a");
addTerm("先", "saki", "さき", "Previous", "n/a");
addTerm("夕", "yuu", "ゆう", "Evening", "n/a");
addTerm("本", "hon", "ほん", "Book", "n/a");
addTerm("文", "fumi", "ふみ", "Text", "n/a");
addTerm("字", "aza", "あざ", "Character", "n/a");
addTerm("学", "mana", "まな", "Study", "n/a");
addTerm("校", "kase", "かせ", "School", "n/a");
addTerm("村", "mura", "むら", "Village", "n/a");
addTerm("町", "machi", "まち", "Town", "n/a");
addTerm("森", "mori", "もり", "Forest", "n/a");
addTerm("正", "tada", "ただ", "Correct", "n/a");
addTerm("水", "mizu", "みず", "Water", "n/a");
addTerm("火", "hi", "ひ", "Fire", "n/a");
addTerm("玉", "tama", "たま", "Gem", "n/a");
addTerm("王", "kimi", "きみ", "King", "n/a");
addTerm("石", "ishi", "いし", "Stone", "n/a");
addTerm("竹", "take", "たけ", "Bamboo", "n/a");
addTerm("糸", "ito", "いと", "Thread", "n/a");
addTerm("貝", "kai", "かい", "Shellfish", "n/a");
addTerm("車", "kuruma", "くるま", "Vehicle", "n/a");
addTerm("金", "kane", "かね", "Gold;Metal", "n/a");
addTerm("雨", "ame", "あめ", "Rain", "n/a");
addTerm("赤", "aka", "あか", "Red", "n/a");
addTerm("青", "ao", "あお", "Blue", "n/a");
addTerm("白", "shiro", "しろ", "White", "n/a");